import { useEffect, useState } from 'react'
import { ImagePlus, Plus, Trash2, X } from 'lucide-react'
import { products as demoProducts } from '../components/ProductGrid'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
const initial = { name: '', category: 'Rims', price: '', image: '', stock: true }
export default function AdminDashboard({ onClose }) { const { isAdmin, loading } = useAuth(); const [products, setProducts] = useState(demoProducts); const [orders, setOrders] = useState([]); const [form, setForm] = useState(initial); const [preview, setPreview] = useState(''); const [notice, setNotice] = useState('')
  useEffect(() => { if (!supabase) return undefined; supabase.from('orders').select('*').order('created_at', { ascending: false }).then(({ data }) => setOrders(data ?? [])); const channel = supabase.channel('orders-live').on('postgres_changes', { event: '*', schema: 'public', table: 'orders' }, () => supabase.from('orders').select('*').then(({ data }) => setOrders(data ?? []))).subscribe(); return () => supabase.removeChannel(channel) }, [])
  const addProduct = (event) => { event.preventDefault(); if (!form.name || !form.price) return; setProducts((current) => [...current, { ...form, id: crypto.randomUUID(), price: Number(form.price), image: preview || 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80' }]); setForm(initial); setPreview(''); setNotice('Product added locally. Connect the products table to persist it.') }
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setPreview(URL.createObjectURL(file)); if (supabase) { const path = `${crypto.randomUUID()}-${file.name}`; const { error } = await supabase.storage.from('product-images').upload(path, file); if (!error) setPreview(supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl) } }
  if (loading) return <main className="grid min-h-screen place-items-center bg-carbon text-gold">Checking access…</main>
  if (!isAdmin) return <main className="grid min-h-screen place-items-center bg-carbon text-center"><div><p className="eyebrow">RESTRICTED</p><h1 className="mt-2 text-3xl font-black">ADMIN ACCESS REQUIRED</h1><button className="cta mt-6" onClick={onClose}>Return to shop</button></div></main>
  return <main className="admin-page"><header className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="eyebrow">CONTROL ROOM</p><h1 className="text-3xl font-black">ADMIN DASHBOARD</h1></div><button className="icon-button" onClick={onClose}><X /></button></header>{notice && <p className="mt-5 rounded border border-gold/30 bg-gold/10 p-3 text-sm text-gold">{notice}</p>}<div className="mt-8 grid gap-7 lg:grid-cols-[.85fr_1.15fr]"><form className="metal-panel rounded-xl p-6" onSubmit={addProduct}><h2 className="text-xl font-bold">Add inventory</h2><div className="mt-5 grid gap-4"><input required value={form.name} onChange={(e) => setForm({...form, name:e.target.value})} placeholder="Product name" /><div className="grid grid-cols-2 gap-3"><select value={form.category} onChange={(e) => setForm({...form, category:e.target.value})}>{['Rims','Tuning','Accessories','Maintenance'].map((item) => <option key={item}>{item}</option>)}</select><input required type="number" value={form.price} onChange={(e) => setForm({...form, price:e.target.value})} placeholder="Price (EGP)" /></div><label className="upload-box">{preview ? <img src={preview} alt="Product preview" /> : <><ImagePlus /> Image preview</>}<input type="file" accept="image/*" onChange={upload} /></label><button className="cta justify-center" type="submit"><Plus size={17} /> Add product</button></div></form><section className="metal-panel overflow-hidden rounded-xl"><div className="border-b border-white/10 p-6"><h2 className="text-xl font-bold">Inventory <span className="text-gold">({products.length})</span></h2></div><div className="overflow-x-auto"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th /></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td className="font-bold">{product.name}</td><td>{product.category}</td><td>EGP {product.price.toLocaleString()}</td><td><button className="text-white/40 hover:text-crimson" onClick={() => setProducts(products.filter((item) => item.id !== product.id))}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div></section></div><section className="metal-panel mt-7 rounded-xl p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Live orders</h2><span className="text-xs text-gold">● REALTIME</span></div><p className="mt-3 text-sm text-white/50">{supabase ? `${orders.length} orders loaded from Supabase.` : 'Add Supabase credentials to enable live orders.'}</p></section></main> }
