import { useState } from 'react'
import { Minus, Plus, ShoppingBag, Trash2, X } from 'lucide-react'
import { useCart } from '../context/CartContext'
const money = (value) => `EGP ${value.toLocaleString()}`
export default function CartDrawer() {
  const { items, count, subtotal, isCartOpen, setCartOpen, updateQuantity, removeItem, checkout } = useCart(); const [details, setDetails] = useState({ name: '', phone: '', governorate: '', address: '' }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const submit = async () => { if (!details.name || !details.phone || !details.governorate || !details.address) { setError('Please add your name, phone, governorate, and delivery address.'); return } setError(''); setSubmitting(true); try { await checkout(details) } catch (err) { const message = err?.message || 'We could not save your order. Please try again.'; setError(message); window.alert(`Order not completed: ${message}`) } finally { setSubmitting(false) } }
  return <><div className={`drawer-scrim ${isCartOpen ? 'visible' : ''}`} onClick={() => setCartOpen(false)} /><aside className={`cart-drawer ${isCartOpen ? 'open' : ''}`} aria-label="Shopping cart"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="eyebrow">YOUR GARAGE</p><h2 className="text-2xl font-black">CART <span className="text-red-500">({count})</span></h2></div><button className="icon-button" onClick={() => setCartOpen(false)}><X /></button></div>{items.length === 0 ? <div className="grid flex-1 place-items-center text-center text-white/45"><div><ShoppingBag className="mx-auto mb-4" size={36} /><p>Your garage is empty.</p></div></div> : <><div className="flex-1 divide-y divide-white/8 overflow-y-auto">{items.map((item) => <div className="flex gap-3 py-5" key={item.id}><img className="h-19 w-19 rounded object-cover" src={item.image} alt="" /><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold">{item.name}</h3><p className="mt-1 font-mono text-xs text-red-500">{money(item.price)}</p><div className="mt-3 flex items-center justify-between"><span className="quantity"><button onClick={() => updateQuantity(item.id, item.quantity - 1)}><Minus size={13} /></button><b>{item.quantity}</b><button onClick={() => updateQuantity(item.id, item.quantity + 1)}><Plus size={13} /></button></span><button className="text-white/35 hover:text-crimson" onClick={() => removeItem(item.id)}><Trash2 size={15} /></button></div></div></div>)}</div><div className="border-t border-white/10 pt-5"><div className="mb-4 grid gap-2"><input className="checkout-input" value={details.name} onChange={(e) => setDetails({ ...details, name: e.target.value })} placeholder="Full name" /><input className="checkout-input" value={details.phone} onChange={(e) => setDetails({ ...details, phone: e.target.value })} placeholder="Phone number" type="tel" /><input className="checkout-input" value={details.governorate} onChange={(e) => setDetails({ ...details, governorate: e.target.value })} placeholder="Governorate" /><input className="checkout-input" value={details.address} onChange={(e) => setDetails({ ...details, address: e.target.value })} placeholder="Delivery address" /></div>{error && <p role="alert" className="mb-3 text-xs text-red-300">{error}</p>}<div className="mb-5 flex justify-between text-sm"><span className="text-white/55">Subtotal</span><b>{money(subtotal)}</b></div><button disabled={submitting} onClick={submit} className="whatsapp-button">{submitting ? 'Saving order…' : 'Checkout via WhatsApp'}</button><p className="mt-3 text-center text-[10px] tracking-wide text-white/35">WE'LL CONFIRM AVAILABILITY & DELIVERY DETAILS</p></div></>}</aside></>
}
